name: ci-demo

# triggers
# Describes the condition on which these jobs should be executed
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Demo: A simple job that prints "Hello World"
  helloworld:
    name: Print Hello World
    # Describes the environment on which this job should run
    runs-on: ubuntu-latest
    # Different steps of this job
    steps:
      - name: hello
        # The CLI command(s) for this job
        run: echo "Hello World"
  
  # # Demo: This job checks whether all .py files in the root directory
  # # begins with CS3213
  # checkprefix:
  #   name: Check Prefix
  #   runs-on: ubuntu-latest
  #   steps:
  #     # This is a marketplace workflow to checkout the current branch
  #     # Without this, you will be working with an empty directory
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     # Below is the actual check
  #     - name: check pref
  #       run: |
  #         if ls *.py 2>/dev/null | grep -qv '^CS3213'; then\
  #           echo "All .py files should begin with CS3213"
  #           exit 1
  #         fi

  # checkdocumentation:
  #   name: Check Documentation
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Checkout the current branch
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     # Set up python environment
  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10'
  #     # Run your test
  #     - name: Check Documentation
  #       run: #TODO: Add your test here (simply call the python file we provided)
